### ISSUE TITLE
Please help! Don;t how to download/use Sector Generator from GutHub

### ISSUE THREAD

**Issue by Asimovian68** [bartlebythecoder/traveller-universe-creator#3]
Hello. Your Sector Generator program looks amazing. I'd like to use it for my homebrew Traveller campaign, but I'm not familiar with GitHub or Python. Can you please let me know how to run it? Thx

**Comment by bartlebythecoder** [comment]
As discussed on COTI - building an exe

**Comment by Asimovian68** [comment]
I don't want to make unnecessary work for you. Can you point me toward a resource for using the program in Python?

**Comment by bartlebythecoder** [comment]
This is a good overview...
https://www.youtube.com/watch?v=mrUPVI6UllE&ab_channel=SneakerHandbook
